config {
  type: "view", // Creates a view in BigQuery. Try changing to "table" instead.
}
 js {
    var { HOME_PAGE_REGEX } = require("includes/constants");
  }

SELECT
   date,
   device,
   stitched_user_id,
   stitched_user_id AS home_page_landed_users,
   page
FROM ${ ref('stg_ga4_landings') }
WHERE REGEXP_CONTAINS(page, r'${constants.HOME_PAGE_REGEX}')
and stitched_user_id is not null
GROUP BY 1, 2, 3, 4,5
